name: queue_manager
description: A List based queue manager for dart and flutter.
version: 1.0.0
homepage: https://github.com/Ayush-Suman/queue_manager

environment:
  sdk: '>=2.17.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
